// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwotHRp7SwBKSiWfQ63p_ixpp2MLIDEZU',
    appId: '1:575368380690:web:c9c00bb9f98cf7128273cb',
    messagingSenderId: '575368380690',
    projectId: 'somernproject',
    authDomain: 'somernproject.firebaseapp.com',
    storageBucket: 'somernproject.appspot.com',
    measurementId: 'G-RE4C6D9BP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSOJqY671ZqelxBSkw3I9zKh-mPL5rod4',
    appId: '1:575368380690:android:431e93b15c93a2678273cb',
    messagingSenderId: '575368380690',
    projectId: 'somernproject',
    storageBucket: 'somernproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVpwd4tLp6SVrZtmffO3rXBSuHpOv9JhI',
    appId: '1:575368380690:ios:e8800cd91a27d2368273cb',
    messagingSenderId: '575368380690',
    projectId: 'somernproject',
    storageBucket: 'somernproject.appspot.com',
    androidClientId: '575368380690-cjh61dentqe96r11v00mcahe4ok5nlka.apps.googleusercontent.com',
    iosClientId: '575368380690-17acrduojg9fro1ec4svqkv2bi4t1cqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterModApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVpwd4tLp6SVrZtmffO3rXBSuHpOv9JhI',
    appId: '1:575368380690:ios:e8800cd91a27d2368273cb',
    messagingSenderId: '575368380690',
    projectId: 'somernproject',
    storageBucket: 'somernproject.appspot.com',
    androidClientId: '575368380690-cjh61dentqe96r11v00mcahe4ok5nlka.apps.googleusercontent.com',
    iosClientId: '575368380690-17acrduojg9fro1ec4svqkv2bi4t1cqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterModApp',
  );
}
